### ISSUE TITLE
Новий датасет

### ISSUE THREAD

**Issue by hladush** [brown-uk/nlp_uk#10]
Привіт я в рамках своєї роботи перевів розмічений датасет imdb на українську мову. Тепер шукаю місце де покласти цей датасет. Мені здається, що ваш проект це гарне місце. 
Опис датасету
28 000 файлів кожне до 1000 символів 
14 000 позитивних текстів і 14 000 негативніх
Файли були отримані шляхом машинного перекладання текстів з англійської. Тексти перекладені частково через брак грошей але цього датасету достатьно для перевірки деяких моделей і це краще ніж нічого. Якщо вам цікаво то напишіть
Якщо ви знаєте місце куди можно покласти датасет то підскажіть

**Comment by arysin** [comment]
Вітання, це цікава робота, але чому Ви думаєте, тут хороше місце викласти цю базу?
І ще я не впевнений, наскільки машинний переклад є добрим матеріалом для моделей.

**Comment by hladush** [comment]
@arysin Дякую за вашу відповідь. Я знайшов два репозиторія, хоч якось підходять для цього і написав їм. Якщо ви знаєте краще місце то скажіть.
Стосовно перекладу, так він не накращий, але я зміг навчити просту рекурентну нейронну мережу на датасеті з 14 тисяч текстів і перевірив її якість на інших 14 тис текстів, точність була 82%. 
У рамках своєї роботи я не знайшов відкритий датасет для української мови такого характеру. Тому вважаю що навіть датасет, який отриманий шляхом машинного перекладу може буди корисний для початкових дослідників, або для тестування ідей.

**Comment by arysin** [comment]
А можна глянути на якусь вибірку з цих даних, щоб оцінити, чи вони тут будуть на своєму місці?

**Comment by hladush** [comment]
@arysin Так звичайно, зараз наведу кілька перших речень з декількох файлів. Ще раз наголошую це машинний переклад на українську мову
Позитивні

> 'Секс, наркотики, расизм і, звичайно, ви ABC. Що ще можна захотіти в дитячому шоу'

> Режисер любить актрису і це показує. Актриса населяє персонажа, якого ми любимо з першого погляду та звучання.

> 
Дивовижно кумедна, вражаюча особливість піонерів туртаблізму. DJ Shadow та Q-Bert вражають цим надзвичайним документальним фільмом. Перегляньте майже кожного головного ді-джея, який зараховує їх на подряпину завдяки класиці Herbie Hancoc

> Я просто хотів би сказати, що The Cure був чудовим фільмом, який допомагає інформувати про те, як люди, які мають ВІЛ-позитивних людей, повинні функціонувати в житті.

> Надзвичайно чарівна Сюзі Делер грає артиста статуї, одержимого успіхом у театрі. Її чоловік і акомпаніатор, якого грає Бернард Блієр, - складна, але ревна людина

Тепер негативні

> Первинний сюжет! Первинний напрямок! Погане тлумачення

> Десять хвилин людей, що лунають галонами рожевої блювоти. Повторювані сцени величезної купи собачих екскрементів - потрібно сказати більше ??

> Zipperface - це такий досвід, якого потрібно чекати протягом усього життя! Мансур Порманд - один з найгірших режисерів усіх часів! Якщо ви любите погані фільми, дивіться це за будь-яку ціну

> УГГ! ... це найгірша боротьба з рестлеманією .... немає хороших матчів ..... Халк Хоган знову в головному заході отримує над засмаглою лисиною голову! Одне зауваження, гідне на цій стрічці. 1 з 10 зірок WOOF !!


> Мушу визнати, що це один з найгірших фільмів, який я бачив. Я думав, що у Деніса Хоппера трохи більше смаку, ніж з'являтися в такому роді yeeeecchh. Якщо це повинно бути смішним, то я повинен оглянути нове почуття гумору. Якщо ви думаєте придбати цей фільм, краще подумайте ще раз

**Comment by hladush** [comment]
Я б дуже хотів поділитись цим датасетом, та знайти йому затишне місце в цьому репозиторію. Бо коли я почав робити свою роботу, то не знайшов жодного відкритого розміченого датасету для аналізу сентименту

**Comment by onyx74** [comment]
@Pryanic Добоий день! Дякую за вашу роботу! Я займаюсь схожою проблематикою, і Ваш датасет дуже мене цікавить. Чи не могли б ви мені його надати?

**Comment by arysin** [comment]
@Pryanic А чому б вам не викласти його в свому репозиторії? На жаль, ми не зможемо займатися його розвитком/підтримкою. А ви його власник, можливо вам варто його мати під своїм контролем?

**Comment by hladush** [comment]
@onyx74  дякую, напішіть мені на пошту diana.melnyk@nure.ua і я вам вишлю датасети. 
@arysin  я хотів віддати його вам з надією, що ви будете його розвивати/підтримувати але якщо це не можливо, то додам до власного репозиторію.

**Comment by arysin** [comment]
@Pryanic На жаль, цей датасет наразі не зовсім вкладається в нашу діяльність, тому ми не зможемо займатися його розвитком.
