### ISSUE TITLE
EvaluateText: хибні помилки "Не узгоджено іменник з дієсловом"

### ISSUE THREAD

**Issue by DSLituiev** [brown-uk/nlp_uk#17]
Перевірник видає помилку в деяких фразах `[іменник] [дієслово-неозначене]`

```
У нього план забігти в супермаркет до комендантської
В мене є бажання подарувати їй квіти
Він має натхнення написати пісню
У всіх там нужда вийти на вихідних
У вас програма поїсти за гроші
```

```
Message:  Не узгоджено іменник з дієсловом: "нужда" (ж.р.) і "вийти" (інф.)
Sentence: в мене є бажання подар…
Position: ^

Message:  Не узгоджено іменник з дієсловом: "програма" (ж.р.) і "поїсти" (інф.)
Sentence: в мене є бажання подар…
Position: ^
```

**Comment by DSLituiev** [comment]
дещо серйозніша проблєма: коли я додаю нові рядки у файл, деякі помилки, що детектувалися раніше, тепер не детектуються. Я змінив попередній зразок на наступне

```
У нього план забігти в супермаркет до комендантської
У нього програма забігти в супермаркет до комендантської
У нього нетерплячка забігти в супермаркет до комендантської
В мене є бажання подарувати їй квіти
Він має натхнення написати пісню
У всіх там нужда вийти на вихідних
У вас програма поїсти за гроші
```

і отримую лише одну помилку

```
Message:  Не узгоджено іменник з дієсловом: "програма" (ж.р.) і "забігти" (інф.)
Sentence: У нього план забігти в…
Position: ^
```

**Comment by DSLituiev** [comment]
Ще одна ітерація видає дива при переміні місцями рядків:

Вхідний файл:

```
У нього план забігти в супермаркет до комендантської
В мене є бажання подарувати їй квіти
Він має натхнення написати пісню
У всіх там нужда вийти на вихідних
У вас програма поїсти за гроші
У нього програма забігти в супермаркет до комендантської
У нього нетерплячка забігти в супермаркет до комендантської
```

Вихідний файл
```
Message:  Не узгоджено іменник з дієсловом: "нужда" (ж.р.) і "вийти" (інф.)
Sentence: У нього план забігти в…
Position: ^

Message:  Не узгоджено іменник з дієсловом: "програма" (ж.р.) і "поїсти" (інф.)
Sentence: У нього план забігти в…
Position: ^

Message:  Не узгоджено іменник з дієсловом: "програма" (ж.р.) і "забігти" (інф.)
Sentence: У нього план забігти в…
Position: ^

Message:  Не узгоджено іменник з дієсловом: "нетерплячка" (ж.р.) і "забігти" (інф.)
Sentence: У нього план забігти в…
Position: ^
```

**Comment by DSLituiev** [comment]
додавання крапок в кінці рядків не змінює останній результат

**Comment by arysin** [comment]
Дякую, додам нужду і програму, такими, що можуть мати наступним інфінітив.

**Comment by arysin** [comment]
Насправді правила не дають 100% правильні збіги, ми намагаємося балансувати між виявлянням помилок і не видаванням забагати фальшивих. Частково це проблема незнятої омонімії, частково складністю мови, гнучким порядком слів у реченні тощо, Тож інколи користувач сам має визначити, чи це справжня помилка, чи ні.
LT розбиває речення за крапками, а параграфи за двома новими рядками. То ж у прикладі вгорі краще мати крапки.
Але я спробую днями глянути глибше на проблему.

**Comment by arysin** [comment]
Вітання, я виправив EvaluateText. Але насправді EvaluateText створювався для досить спеціалізованої мети: відбирання кращих текстів для корпусу. Чи не могли б ви описати кінцеву мету вашого проєкту?

**Comment by DSLituiev** [comment]
Дякую! Протестую. Моє застосування -- для порівняння якості ASR моделей. Корпус в мене розмовний (інтервʼю).

**Comment by arysin** [comment]
Гаразд, там наразі ми деякі правила ігноруємо (див. RULES_TO_IGNORE), може для ваших цілей варто якісь увімкнути назад. В будь-якому разі пишіть, як воно працює, спробую допомогти.

**Comment by DSLituiev** [comment]
Було б класно видавати ідентифікацію правил (rule ID), щоб можна було фільтрувати

**Comment by arysin** [comment]
Додав
