### ISSUE TITLE
Error on project building

### ISSUE THREAD

**Issue by rmotsar** [brown-uk/nlp_uk#3]
> Error:(32, 0) Could not get unknown property 'ltDir' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

In all .gradle file/git repository any comments about this variable

**Comment by arysin** [comment]
You can run groovy script directly - you don't need to build with gradle (just need a network for the first run to download dependencies). 
I've updated the script and docs to make it more clear.

**Comment by rmotsar** [comment]
@arysin thanks
