### ISSUE TITLE
Wrong tagging of initials by TagText.groovy script

### ISSUE THREAD

**Issue by secorplex** [brown-uk/nlp_uk#6]
Used command groovy TagText.groovy -i <input_file> -o <output_file>

Input file [in.txt](https://github.com/brown-uk/nlp_uk/files/1792293/in.txt)
Output file [out.txt](https://github.com/brown-uk/nlp_uk/files/1792295/out.txt)

A letter 'В' is wrongly tagged as a preposition, but actually it is an initial of proper name of 'Бондар'.

**Comment by arysin** [comment]
Thanks, it seems to work properly when initials have space between them but not without. Will take a look, hopefully we can have it fixed before next release of LanguageTool.

**Comment by arysin** [comment]
Finally got some time to fix this so should be working properly in the next version of LanguageTool engine (4.3).
