### ISSUE TITLE
Не працює параметр --firstLemmaOnly у лематизаторі

### ISSUE THREAD

**Issue by OlexaD** [brown-uk/nlp_uk#9]
Добрий день, пане Андрію. Я перепрошую, що знов турбую Вас :) але у мене знов виникла проблема, цього разу з лематизатором. Не працює параметр -f або --firstLemmaOnly. Я пробував обидва варіанти. Все одно, у вихідному файлі .lemmatized присутні всі варіанти для омонімів. Дякую за допомогу.

**Comment by arysin** [comment]
Дякую, що повідомили, виправив.
